
DELIMITER // 
CREATE FUNCTION Hello ()
RETURNS VARCHAR(255) DETERMINISTIC
BEGIN
	DECLARE dt VARCHAR(255);
	CASE WHEN CURRENT_TIME() BETWEEN '06:00:00' AND '11:59:59' THEN 
	SET dt = 'Good morning';
	WHEN CURRENT_TIME() BETWEEN '12:00:00' AND '17:59:59' THEN 
	SET dt = 'Good day';
	WHEN CURRENT_TIME() BETWEEN '18:00:00' AND '23:59:59' THEN 
	SET dt = 'Good evening';
	ELSE SET dt = 'Goodnight';
	END CASE;
RETURN dt;
END //

SELECT Hello();